name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@main
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
