name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/extension-test.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}